"""Initial schema

Revision ID: 45bb6cbbe59b
Revises: 
Create Date: 2025-12-29 23:42:07.920321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bb6cbbe59b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_owner', sa.Text(), nullable=False),
    sa.Column('receiving_party', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('active', 'pending', 'accepted')", name='handoff_state_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handoff_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=True),
    sa.Column('to_state', sa.Text(), nullable=True),
    sa.Column('previous_owner', sa.Text(), nullable=True),
    sa.Column('new_owner', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handoff_id'], ['handoffs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handoff_events')
    op.drop_table('handoffs')
    # ### end Alembic commands ###
