"""receiving_party nullable

Revision ID: f8d8b2676472
Revises: 45bb6cbbe59b
Create Date: 2025-12-30 15:40:31.448419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d8b2676472'
down_revision: Union[str, Sequence[str], None] = '45bb6cbbe59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('handoffs', 'receiving_party',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('handoffs', 'receiving_party',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
